modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "UNLICENSED"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Treecipe"
credits = "JEI and related, Soaryn"
authors = "FiniteReality"
description = '''
A tree-based recipe viewer with an extensive API.
'''

[[mixins]]
config = "treecipe.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "jei"
type = "optional"
versionRange = "${jei_version}"
ordering = "AFTER"
side = "CLIENT"